name: Publish Release Notes to Docs

on:
  release:
    types: [published]  # trigger only when a release is published

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout analytics repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone to zeotap-web-sdk-docs repo
        run: |
          git clone "https://x-access-token:${{ secrets.SDK_DOC_REPO_TOKEN }}@github.com/rishabh-zeo/zeotap-web-sdk-docs.git" docs-repo

      - name: Create release notes file
        run: |
          cd docs-repo
          branch_name="release-notes-${{ github.event.release.tag_name }}"
          git checkout -b $branch_name

          mkdir -p mydocs/releasenotes
          echo "${{ github.event.release.body }}" > mydocs/releasenotes/${{ github.event.release.tag_name }}.md

          git add mydocs/releasenotes/${{ github.event.release.tag_name }}.md
          git commit -m "Add release notes for ${{ github.event.release.tag_name }}"
          git push origin $branch_name

      - name: Create a Pull Request
        run: |
          cd docs-repo
          gh pr create --title "Add release notes for ${{ github.event.release.tag_name }}" \
                       --body "This PR adds release notes for ${{ github.event.release.tag_name }}" \
                       --head $branch_name \
                       --base main
        env:
          GH_TOKEN: ${{ secrets.SDK_DOC_REPO_TOKEN }}
